### PR TITLE
Will branch

### PR DESCRIPTION
**Pull request by WilliamBrickner**
These are some basic things but include the <conio.h> this include will allow us to use _getch(). _getch() automatically will take the first char/ int and use that for the input. Other than that I think thats all that is "new". If you want me to change anything just say so.

### CODE REVIEW

**Review by Tacotime2 — APPROVED** [review]
Looks good, I will implement the input change in my code.

**Review by Tacotime2 — DISMISSED** [review]
For some reason it didn't look like the last review approved.

**Review by CrispyTwilight — APPROVED** [review]
The client was not changed, so the program still compiles. These classes will need a bit more work before an instance can be created, but merge approved for now.

**Review by WilliamBrickner — COMMENTED** [review]
Seems good.

**Pull request merged**
